import 'controller/booking_six_controller.dart';import 'package:flutter/material.dart';import 'package:medikas3/core/app_export.dart';import 'package:medikas3/widgets/custom_button.dart';import 'package:medikas3/presentation/booking_five_dialog/booking_five_dialog.dart';import 'package:medikas3/presentation/booking_five_dialog/controller/booking_five_controller.dart';
// ignore_for_file: must_be_immutable
class BookingSixDialog extends StatelessWidget {BookingSixDialog(this.controller);

BookingSixController controller;

@override Widget build(BuildContext context) { return GestureDetector(onTap: () {onTapColumncheckmark();}, child: Container(padding: getPadding(left: 37, top: 48, right: 37, bottom: 48), decoration: AppDecoration.fillWhiteA700.copyWith(borderRadius: BorderRadiusStyle.circleBorder18), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(svgPath: ImageConstant.imgCheckmark, height: getSize(36.00), width: getSize(36.00)), Padding(padding: getPadding(left: 12, top: 8, bottom: 5), child: Text("msg_payment_successful".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtLatoBold18))]), Padding(padding: getPadding(top: 25), child: Text("msg_appointment_booked".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtLatoBold16)), Padding(padding: getPadding(top: 7), child: Text("msg_your_appointment".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtLatoMedium14Gray900)), Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: getMargin(top: 14), color: ColorConstant.whiteA700, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.circleBorder32), child: Container(height: getSize(64.00), width: getSize(64.00), padding: getPadding(all: 5), decoration: AppDecoration.outlineBlack90028.copyWith(borderRadius: BorderRadiusStyle.circleBorder32), child: Stack(children: [CustomImageView(imagePath: ImageConstant.imgUsmanyousafpt, height: getSize(53.00), width: getSize(53.00), radius: BorderRadius.circular(getHorizontalSize(26.00)), alignment: Alignment.center)]))), Padding(padding: getPadding(top: 6), child: Text("msg_dr_mohan_shukla".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtLatoSemiBold16GreenA200.copyWith(height: 1.25))), Padding(padding: getPadding(top: 9), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(svgPath: ImageConstant.imgCalendar, height: getSize(20.00), width: getSize(20.00), margin: getMargin(bottom: 1)), Padding(padding: getPadding(left: 8, top: 1), child: Text("lbl_fri_jan_07".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtLatoMedium16.copyWith(height: 1.25))), CustomImageView(svgPath: ImageConstant.imgClock, height: getSize(20.00), width: getSize(20.00), margin: getMargin(left: 24, top: 1)), Padding(padding: getPadding(left: 8, bottom: 1), child: Text("lbl_serial_no_16".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtLatoMedium16.copyWith(height: 1.25)))])), CustomButton(height: 64, width: 250, text: "lbl_done".tr, margin: getMargin(top: 31))]))); } 
onTapColumncheckmark() { Get.defaultDialog(title: '', backgroundColor: Colors.transparent, content:BookingFiveDialog(Get.put(BookingFiveController(),),),); } 
 }
